name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true  # Use Go cache in order to speed up the build

      - name: Install dependencies
        run: go mod tidy

      - name: Run static analysis (golangci-lint)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          $(go env GOPATH)/bin/golangci-lint run ./...

      - name: Check code formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then 
            echo "Code is not formatted. Run 'go fmt ./...'"; 
            exit 1; 
          fi

      - name: Run tests
        run: make test

  docker:
    needs: test  # Ne construit l'image Docker que si les tests passent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t terralambda .

      - name: Run Docker tests
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            terralambda test 